###############################################################################
#
#   Main software to be installed in the environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Biozentrum_University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 22-01-2020
#   LICENSE: GPL
#
###############################################################################
---

channels:
  - bioconda
  - conda-forge

dependencies:
  - rna-seqc=2.3.5
  - bx-python=0.8.6
  - pandas=0.25.3

...