###############################################################################
#
#   Main software to be installed in the environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Biozentrum_University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 20-01-2020
#   LICENSE: GPL
#
###############################################################################
---

channels:
  - bioconda
  - conda-forge

dependencies:
  - r-base=3.5
  - r-optparse=1.6.0
  - r-rcpp=1.0.1
  - r-grimport=0.9_2
  - readline=7.0
  - r-maxlik=1.3_4
  - r-rcolorbrewer=1.1_2
  - r-gplots=3.0.1

...