###############################################################################
#
#   Main software to be installed in the environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: Biozentrum_University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: maciej.bak@unibas.ch
#   CREATED: 20-01-2020
#   LICENSE: GPL
#
###############################################################################
---

channels:
  - bioconda
  - conda-forge

dependencies:
  - python=3.6.3
  - numpy=1.15.2
  - pandas=0.21.0
  - pyyaml=3.12
  - scipy=1.0.0
  - matplotlib=3.1.0
  - seaborn=0.8.1
  - statsmodels=0.10.2
  - pybedtools=0.7.10
  - htseq=0.12.4
  - pymongo=3.2.2
  - jinja2=2.10

...